name: Job Scraper Bot

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour
  workflow_dispatch: # Allows manual trigger

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install aiohttp gspread feedparser google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client requests

      - name: Run Job Scraper
        env:
          GOOGLE_SHEET_CREDS: ${{ secrets.GOOGLE_SHEET_CREDS }}
          SAPI: ${{ secrets.SAPI }}
          CXAPI: ${{ secrets.CXAPI }}
          GAPI1: ${{ secrets.GAPI1 }}
          GAPI2: ${{ secrets.GAPI2 }}
          GAPI3: ${{ secrets.GAPI3 }}
          GAPI4: ${{ secrets.GAPI4 }}
          GAPI5: ${{ secrets.GAPI5 }}
          GAPI6: ${{ secrets.GAPI6 }}
          GRAPI1: ${{ secrets.GRAPI1 }}
          GRAPI2: ${{ secrets.GRAPI2 }}
          GRAPI3: ${{ secrets.GRAPI3 }}
          GRAPI4: ${{ secrets.GRAPI4 }}
          GRAPI5: ${{ secrets.GRAPI5 }}
          GRAPI6: ${{ secrets.GRAPI6 }}
          TOK: ${{ secrets.TOK }}
          ID: ${{ secrets.ID }}
          USER_PROFILE_INFO: ${{ secrets.USER_PROFILE_INFO }}
        run: python main.py
